cas:
    path: /cas
    controller: Viduc\CasBundle\Controller\CasController::index

enTantQue:
    path: /en_tant_que
    controller: Viduc\CasBundle\Controller\EnTantQueController::connecterEnTantQue

enTantQueRestore:
    path: /en_tant_que_restore
    controller: Viduc\CasBundle\Controller\EnTantQueController::restaurerEnTantQue

personaIndex:
    path: /persona
    controller: Viduc\CasBundle\Controller\PersonaController::index

personaSeConnecter:
    path: /personaSeConnecter/{id}
    controller: Viduc\CasBundle\Controller\PersonaController::seConnecter

personaRestore:
    path: /personaRestore
    controller: Viduc\CasBundle\Controller\PersonaController::restaurerEnTantQue

personaAjouter:
    path: /personaAjouter
    controller: Viduc\CasBundle\Controller\PersonaController::ajouterUnPersona

personaModifier:
    path: /personaModifier/{id}
    controller: Viduc\CasBundle\Controller\PersonaController::modifierUnPersona