language: php
php:
- '7.2'
env:
  global:
  - CC_TEST_REPORTER_ID=6c93a972033b86464ae4d510468f04e4b3bda78f8184780b8af0b6d6d7aa8600
  - secure: GPogiQXdpVkEcysSiuvsnodgbbCY/72Pkbu7O9LjxVRyLBkumR27WhuqwI3qd+3eHDzXkC9sFwQn2mzmqGlHRbLjPF/n5xDEW6/3nKwWIYsWoBsAQcwG/Nt3dhoKFh+pbQYjtLSbNSvSUofOv3P+hqzD4wegx66OaXgO/+Yr3DCkdiW6swI1vC1Hw42rtj5Rd1NhTf9np9vfwGfENRkzzaWLKVYS9pFgtHec1zFLpygVkUkWVrsyEWxH2LnC75MZ3uJVq1zrm/DJNHI/X0QhQYvPnSbx45OYyhLUmczaLLzWfZlnFjYKaasKlKlVN7GJpPruDke+YNOCs7FGEYLkXYtS/d5rZtFzrvJSfomlUyEHQI2MQOUyXC2TcQj4xQ40ay/sp9p1ih9fqS1jijOARZePUKNfUNST85GcSU8+RB6hMrVeHy53wg/WBDHSwds69eXEA2fYXJZJXg49bKOlQNQa//Xd2YkORRVYqBZznAHMOcKYkZS5OLSeBilRw5d+4x16KqlxX4zGcL9Y6IvXVR8+NxKBruQ+UA7wodZfQXR8wFtsQaYJgh5X9HhOTzN0WFw5XDIcH3kI5Pq3ENKk9azTgyr1cAKDK3jku4hAJ3Gwrgf4/SCyjahdIg0SKSypJomXPT4IXrDlxnSuUaH5TYRokECO8Kp38Jx6f1xejk0=
addons:
  sonarcloud:
    organization: "viduc"
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
script:
- composer install
- composer require symfony/phpunit-bridge:3.4.42
- composer require symfony/http-foundation:3.4.42
- composer require symfony/framework-bundle:3.4.42
- composer require symfony/security-core:3.4.42
- composer require symfony/console:3.4.42
- composer require codeclimate/php-test-reporter
- composer require symfony/serializer
- composer require symfony/property-access
- vendor/bin/phpunit --coverage-clover=clover.xml
- sonar-scanner
after_script:
- "./cc-test-reporter after-build -t clover --exit-code $TRAVIS_TEST_RESULT"
- cp clover.xml coverage.xml
after_success:
- bash <(curl -s https://codecov.io/bash)
