language: php
php:
  - '7.2'
  - '7.3'
script:
  - composer install
  - composer require symfony/phpunit-bridge:3.4.42
  - composer require symfony/http-foundation:3.4.42
  - composer require symfony/framework-bundle:3.4.42
  - composer require symfony/security-core:3.4.42
  - composer require symfony/console:3.4.42
  - composer require codeclimate/php-test-reporter
  - vendor/bin/phpunit --coverage-clover=coverage.xml
after_success:
  # Submit coverage report to https://codecov.io
  - bash <(curl -s https://codecov.io/bash)