language: php
php:
  - '7.2'
  - '7.3'
addons:
  code_climate:
    repo_token:
      secure: "eGeq4Up/4JoBg+k3XIJCMVj573AIlhoOGLAsz0Cy4JBlxAVdpI4/hhcTRrrWYTjO9q0u2AhkNm3i7SGRqoXUN7+LNK5UtdvyDrXC553l5HVQy5TaELNyYe7jVNeLND2uPZ/IKIywvrMRrVlMENkYRwtzjv0nPjpvpTm3Y7uP8HqYXpqTmMqRVDrXXoJCxTj3hFP39fg7QhIdVzVAMGaSUMyV3dI9zBonkyj4TUBQF3VJYm416IdW7CEEspxzzvQg0jgSEB+U2AboMsjEncZZwhRB1SZXB3uu9qQKTLllKfvo+jVHADiWwO76byRy+M67STXxPZF6ySyVa7V80Yz2QShaHtj2mbu7SqtheAJATSSi9yDMigYiQHwHvU4l/O6Cus2ldo+JWJE1TYBZt2tYPYPzUhoWjb7YmldZ1SWBfeIGlH1sKShs4thN0M7CgRoEpjmxK2QmKfZedjek+KLk6tMKkbwJZJvE7jbVEVgP9HZrw8mh/qWCERNt1vwYukz3MTQNJZPf4nFstiFzEp6JHB5aRpdoxW1wUbXCwyRL5RnCeiXLoAOaWxL9cVHKQtRJFM7BJ31qVuDNvd0KZSVoGS8Dr7IZIe12L+o5kDqoDWL3HbUc9/fYbEv+758gog7V8holV5XfMtWxl5X/CR7hoRvWEhcGArhXbE9tT+iCw7o="

script:
  - composer install
  - composer require symfony/phpunit-bridge:3.4.42
  - composer require symfony/http-foundation:3.4.42
  - composer require symfony/framework-bundle:3.4.42
  - composer require symfony/security-core:3.4.42
  - composer require symfony/console:3.4.42
  - composer require codeclimate/php-test-reporter
  - vendor/bin/phpunit --coverage-clover=coverage.xml
after_success:
  # Submit coverage report to https://codecov.io
  - bash <(curl -s https://codecov.io/bash)