language: php
php:
  - '7.2'
  - '7.3'

script:
  - composer install
  - composer require symfony/phpunit-bridge
  - composer require symfony/http-foundation
  - composer require framework-bundle
  - composer require security-core
  - vendor/bin/phpunit
