language: php
php:
  - '7.2'
  - '7.3'

script:
  - composer install
  - composer require symfony/phpunit-bridge
  - composer require symfony/http-foundation
  - composer require symfony/framework-bundle
  - composer require symfony/security-core
  - vendor/bin/phpunit --coverage-clover=coverage.xml
  - vendor/bin/phpcs --file-list=phpcs --report-file='checkstyle.xml' --report=checkstyle --standard=PSR2 --extensions=php

after_success:
  # Submit coverage report to https://codecov.io
  - bash <(curl -s https://codecov.io/bash)